### ISSUE TITLE
"Cache_hit_percent" showing wrong values

### ISSUE THREAD

**Issue by shakalandy** [andytinycat/check_varnish.pl#2]
We made the observation that in our case (varnish 2.1.5) the values reported by cache_hit_percent show wrong values (something around 33%) whereas when we watch the server with "varnishstat" the hit-rate is more around 75%.

Could it be possible that the usage of "varnishstat -1" in your script is showing wrong values because "varnishstat" takes some seconds to "warm up" and show the real value?

**Comment by andytinycat** [comment]
I can't really reproduce this very easily, as I don't have a Varnish 2.x installation. Your theory may well be correct. Rather than support 2.x, where the varnish\* tools were still a bit buggy, I'd suggest you look at upgrading to 3.x (which has vast improvements over 2.x).
